### ISSUE TITLE
Redirect link on run node guide is pointing to wrong github

### ISSUE THREAD

**Issue by Megumiiiiii** [kroma-network/kroma#109]
### Issue Type

Documentation Feature Request

### Kroma Version

0.2.1

### Current Behaviour?

Update your guide on docs

https://docs.kroma.network/developers/running-kroma-node#3.-setup

### Standalone code to reproduce the issue

404 this is not the page you are looking for

https://docs.kroma.network/developers/running-kroma-node#3.-setup

It's not poiting to anything https://github.com/kroma-network/kroma-up

Update the guide to run node on testnet, not devnet

**Comment by chokobole** [comment]
This is because `kroma-up` is a private repo. Could you tackle this issue @0xHansLee @i-am-yona22 ?

**Comment by 0xHansLee** [comment]
Thank you for reporting this. We'll handle it soon!

**Comment by 0xHansLee** [comment]
The `kroma-up` repository is transitioned to public, so you can access it.
