### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by tynes** [kroma-network/kroma#130]
You are in copyright violation of the MIT license. Please add the Optimism copyright back to all of the license files in this repo.

An example of a violation can be found [here](https://github.com/kroma-network/kroma/blob/dev/LICENSE#L3). An example of the license that should be included can be found [here](https://github.com/ethereum-optimism/optimism/blob/develop/LICENSE).

**Comment by Pangssu** [comment]
Thank you for letting us know about the issue.
This issue will be fixed in PR #131.

**Comment by Pangssu** [comment]
Merged
