### ISSUE TITLE
Block Hash mismatch

### ISSUE THREAD

**Issue by hdiass** [kroma-network/kroma#226]
### Issue type

Bug

### Kroma version

v0.2.1

### OS platform and distribution

docker (kromanetwork/geth:v0.2.1)

### Current behavior?

Hello,

I have a couple of kroma nodes synced, but when i query for a block and compare the hash with the explorer they don't match, but only the hash. Block number and so on match.
Used snapshot to bootstrap.

```
curl -s -m 2 -N -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' "http://mynode" | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "baseFeePerGas": "0x32",
    "difficulty": "0x0",
    "extraData": "0x",
    "gasLimit": "0x1c9c380",
    "gasUsed": "0xc0ed",
    "hash": "0xe87bd7fb8a651eea539c95a9288cbb4f34b2d7314a0a7563644cef54ba1d8c2c",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0x0000000000000000000000000000000000000000",
    "mixHash": "0x5638e0d5f20da2875e6dfcadf771b8b9a04346566d90f3913e2352abc1f85751",
    "nonce": "0x0000000000000000",
    "number": "0x2a7eaa",
    "parentHash": "0x5728ca7525b2f8a5b5e78e7c372af2723559c21a3e4f6e95f1baa6642fea195b",
    "receiptsRoot": "0x38d97aafa05d0cb6f190ddd4b43dc3c523f0d87ad0f2ba69bd1bfe774b4292bb",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0x384",
    "stateRoot": "0x1a0274389596a29534023a977e7d5765f9e19fbf26551613e3c043b4a001fcc1",
    "timestamp": "0x654b8d97",
    "totalDifficulty": "0x0",
    "transactions": [
      "0x9803952ff8940bd3adb2e2e2cddb8ddd3efae152342966c9e718baef46eb80cc"
    ],
    "transactionsRoot": "0x7ccdd625aa7ecc16b836b9670e50d1e67f85a0405656e0738ce78bf270bff514",
    "uncles": []
  }
}
```

If you compare with https://blockscout.kroma.network/block/0x0eab28988b8bf9b8efb68e6269da8f7f2d5d9319c283103be259279f3c46aa02
the hash are not the same. Whats more strange is that the Tx in it match. Am i missing something here ?

Thanks,
HD

### Expected Behavior?

The tx hash from rpc should match the one in explorer.

### Standalone code or description to reproduce the issue

Just curl to get last block details and compare with explorer

### Additional context

running with kromanetwork/node:v1.0.0

**Comment by 0xHansLee** [comment]
Thank you for reporting the issue. 
I wonder which version of kroma-node you used. The version of kroma-node in `Kroma version` and `Additional context` is different.

**Comment by hdiass** [comment]
Sorry, i was tried both kromanetwork/node:v1.0.1 and v1.0.0 with same output

**Comment by Pangssu** [comment]
@hdiass Do you know or can you find where the block hash was different for the first time?
If you don't know, could you please open your RPC endpoint publicly and share it with my email?

**Comment by hdiass** [comment]
Well i'm not sure how can i find that, but just sent the endpoints URLs to the email in your bio.

**Comment by Pangssu** [comment]
Can you find the message `Optimally queuing unsafe L2 execution payload` in the console logs of a recent `kroma-node`?

**Comment by hdiass** [comment]
Yes, here is an example
```
t=2023-11-09T17:02:31+0000 lvl=info msg="Optimistically queueing unsafe L2 execution payload" id=0x469c24eb9763014a9009863a4d2668626090d5cefb1ffc770eefe10a927a9bff:2834482
```

**Comment by hdiass** [comment]
The words are a bit diff, is that you are looking for ?

**Comment by Pangssu** [comment]
Oh, there was a typo in the message I gave you. You're right

**Comment by Pangssu** [comment]
I noticed that the block hash is different from the block after `safe` block. 
Once the sequencer submits batches and your node receives it and proceeds with the derivation, it should be normalized.
However, there does seem to be an issue, and I'd like to take a look at this with my team and get back to you.

**Comment by Pangssu** [comment]
Can you open the endpoint you emailed me to the public until this issue is resolved?

**Comment by hdiass** [comment]
Yes I'll leave it open

**Comment by Pangssu** [comment]
Can you also provide the endpoint of the L1 RPC by email?
And we need your `kroma-node` logs, please provide about 20 minutes of logs.

**Comment by hdiass** [comment]
Its our internal L1 RPC. (geth)
Sending logs via email.

**Comment by Pangssu** [comment]
Did you use our [kroma-up](https://github.com/kroma-network/kroma-up) repository to trigger the chain, or [this link?](https://docs.kroma.network/developers/running-nodes-on-kroma/running-a-full-node)

**Comment by hdiass** [comment]
None of them, ported the docker compose to kubernetes

**Comment by hdiass** [comment]
Can give you the flags I used tho

**Comment by Pangssu** [comment]
My guess is that you have `kroma-node` running in **proposer mode**. Please delete the `NODE_PROPOSER_ENABLED` flag or set it to false.
And please refer to [kroma-up](https://github.com/kroma-network/kroma-up) repository to port to kubernetis.

**Comment by hdiass** [comment]
```
command:
      - kroma-node
    args:
      - --l1=wss://internal-node
      - --l2=http://127.0.0.1:8551
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --l2.jwt-secret=/setup/jwt.txt
      - --p2p.advertise.ip=$EXTERNAL_IP
      - --p2p.listen.tcp=$EXTERNAL_PORT_1
      - --p2p.listen.udp=$EXTERNAL_PORT_1
      - --metrics.enabled
      - --metrics.port=8080
      - --rollup.config=/setup/rollup.json
      - --rpc.enable-admin=true
      - --proposer.enabled=true
      - --syncer.l1-confs=4
      - --p2p.bootnodes="enr:-J24QIRQ_Sxsn08UW2djuM7XIiKMqDnjIRmZV3Y82aBxI396bIligpv716MNmEDitgiNzTYLx9pWVBZUmBLGZao3cJKGAYpjUHvsgmlkgnY0gmlwhA3RbWiHb3BzdGFja4P_AQCJc2VjcDI1NmsxoQO6Fg_lxKa4bqrCTRndRjP6V0Ahh_CduFC4c4khUSiRK4N0Y3CCIyuDdWRwgiMr,enr:-J24QJ0TyKGwcMuY4PCVe7Qo77pSMMkFHMHHZG5IZTtfURttM7by94vRPmFZzlteuCESo8KQC7GxEUKtRxK9dXQpvpGGAYpjUH99gmlkgnY0gmlwhAMldxyHb3BzdGFja4P_AQCJc2VjcDI1NmsxoQJXGyNhwNUSIdGsWbLChN6a47_bfRBFlFCARgjHnl6r-YN0Y3CCIyuDdWRwgiMr"
      - --l1.trustrpc
      - --p2p.security=none
```
and for kroma geth
 ```
     set -exu

      wget https://raw.githubusercontent.com/kroma-network/kroma-up/main/config/mainnet/genesis.json

      if [ ! -d "/database/geth/chaindata" ]; then
        echo "/database missing, running init"
        echo "Initializing genesis."
        geth --verbosity="3" init --datadir="/database" "/genesis.json"
      else
        echo "/database/geth/chaindata exists."
      fi
      geth --verbosity="3" init --datadir="/database" "/genesis.json"
      exec geth \
        --gcmode=archive \
        --trace.mptwitness=1  \
        --circuitparams.maxtxs=0  \
        --gpo.maxprice=100000000  \
        --bootnodes="enode://acf4af39e9d9f3bbdb700315fde6e909efc714bd9a012b0f6943c4f9110008e3da2cb6c2ac9d3b6d98184a5ead57c4409be4ae7b19da1f554ceee7ba86c1fc2e@p2p-0.kroma.network:30304?discport=30303,enode://a3b6a7087b3399eefdb1ce5870aa0e58a60bfeccf3f7f7c02f5e142b1a544d19c171f7688d08db786d5e9b3ba734482bf8cf29dab7d46917b9da7f61656fde39@p2p-1.kroma.network:30304?discport=30303"  \
        --networkid=255  \
        --ws  \
        --ws.port=8546 \
        --ws.addr=0.0.0.0 \
        --ws.origins=* \
        --ws.api="debug,eth,txpool,net,engine,kroma" \
        --http \
        --http.port=8545 \
        --http.addr=0.0.0.0 \
        --http.api="web3,debug,eth,txpool,net,engine,kroma" \
        --http.vhosts=* \
        --http.corsdomain=* \
        --authrpc.addr=localhost \
        --authrpc.jwtsecret=/node/jwt.txt \
        --authrpc.port=8551 \
        --authrpc.vhosts=* \
        --datadir=/database \
        --metrics \
        --metrics.addr=0.0.0.0 \
        --verbosity=3 \
        --syncmode=full \
        --snapshot=false \
        --nat=extip:$EXTERNAL_IP \
        --port=$EXTERNAL_PORT_0
```

**Comment by hdiass** [comment]
I dont set any env vars, do you have the cli flag for that ?

**Comment by Pangssu** [comment]
Remove ` - --proposer.enabled=true`

**Comment by hdiass** [comment]
From CLI help command 
```
   --proposer.enabled             (default: false)
          Enable proposing of new L2 blocks. A separate batch submitter has to be deployed
          to publish the data for syncers. [$NODE_PROPOSER_ENABLED]
   ```

**Comment by hdiass** [comment]
its disabled by default

**Comment by hdiass** [comment]
ah ok will remove that

**Comment by hdiass** [comment]
Does it require resync ?

**Comment by hdiass** [comment]
Ah that was probably a mistake of mine copying the flags :D

**Comment by hdiass** [comment]
Ok, i've removed the flag, let it soak for a few minutes then

**Comment by hdiass** [comment]
Thanks a lot for your help

**Comment by Pangssu** [comment]
No problem :)
I strongly recommend setting the environment variables as is in the `kroma-up` repository.
