### ISSUE TITLE
My bridge fund hacked 

### ISSUE THREAD

**Issue by itsjhonabd** [kroma-network/kroma#253]
### Issue type

Others

### Kroma version

V1.02.1

### OS platform and distribution

Linux.01.07

### Go version

Linux/amg

### Node version

V14/646.01

### Current behavior?

My fund hacked 
![image_1707644042411405](https://github.com/kroma-network/kroma/assets/129699797/5e8ab888-d923-4526-85d5-8e24abff711f)

### Expected Behavior?

Hello sir ,
I withdraw funds kroma-eth mainnet .today when i try to  finalize my withdrawal trancetion my eth sent to someone (hacker wallet).
Is this your bridge problem or what kindly check it out .
And I saw this address recived eth from Manny kroma bridge user 
My address: 0x55A152f1d32eFe2aB6B1f5475E9490758e70DD00
Hacker address: 0xf0f8073f7Dd4CD161c2F1634b6F8A584634d25f7

### Standalone code or description to reproduce the issue

Hello sir ,
I withdraw funds kroma-eth mainnet .today when i try to  finalize my withdrawal trancetion my eth sent to someone (hacker wallet).
Is this your bridge problem or what kindly check it out .
And I saw this address recived eth from Manny kroma bridge user 
My address: 0x55A152f1d32eFe2aB6B1f5475E9490758e70DD00
Hacker address: 0xf0f8073f7Dd4CD161c2F1634b6F8A584634d25f7

### Additional context

Hello sir ,
I withdraw funds kroma-eth mainnet .today when i try to  finalize my withdrawal trancetion my eth sent to someone (hacker wallet).
Is this your bridge problem or what kindly check it out .
And I saw this address recived eth from Manny kroma bridge user 
My address: 0x55A152f1d32eFe2aB6B1f5475E9490758e70DD00
Hacker address: 0xf0f8073f7Dd4CD161c2F1634b6F8A584634d25f7

**Comment by Pangssu** [comment]
Hi itsjhonabd,
Did you notice that the approval popup in the Wallet app (e.g. Metamask) opened twice when you approved the withdrawal finalize transaction?

**Comment by Pangssu** [comment]
I'm closing this issue due to no response. If you have anything to add, please reopen this issue.
