### ISSUE TITLE
Integrate Kroma Chain into Bungee exchange to enhance visibility and facilitate easy bridging through their exchange.

### ISSUE THREAD

**Issue by timurg405** [kroma-network/kroma#258]
### Issue type

Others

### Kroma version

v1

### Current behavior?

Kroma Network, which is one of the players in Layer 2 but lacks recognition among general users. To increase visibility and attract new users, it would be desirable to have more opportunities to send funds to the Kroma network through popular and frequently used exchanges.

### Expected Behavior?

After these actions and integrations, interest in the project will increase, along with a new influx of funds and activities.

### Standalone code or description to reproduce the issue

.

**Comment by Pangssu** [comment]
Thank you. I'll pass this feedback on to our team.
