### ISSUE TITLE
Mainnet stuck on block 9029806

### ISSUE THREAD

**Issue by timweri** [kroma-network/kroma#283]
### Issue type

Bug

### Kroma version

v1.3.3

### Current behavior?

My Kroma node was stuck on block 9029806 for 10 minutes. I went to check kromascan.com and seems like the latest block has been 9029806 for 30+ mins and counting.

### Expected Behavior?

A new block is produced every ~2s

### Standalone code or description to reproduce the issue

<img width="748" alt="Screenshot 2024-03-31 at 23 29 54" src="https://github.com/kroma-network/kroma/assets/9196362/01e709da-e378-4707-957a-bc1d59435733">

**Comment by 0xHansLee** [comment]
A fork has occurred on Kroma mainnet, and now it is resolved. If you run a full node or validator, please restart your node. If you have any issues remained, please reopen this issue. Thank you.
