### ISSUE TITLE
Kroma-Validator TLS Error

### ISSUE THREAD

**Issue by SethCalkins** [kroma-network/kroma#292]
### Issue type

Bug

### Kroma version

1.3.4

### OS platform and distribution

Ubuntu 20.04

### Current behavior?

I'm currently running a local RPC mainnet Execution (Geth) / Consensus (Prysm) on my local network and attempting to connect kroma-validator to it but I'm getting the following error.

`kroma-validator  | t=2024-04-06T14:29:38+0000 lvl=warn msg="Unknown env var" prefix=VALIDATOR env_var="VALIDATOR_LOG_TERMINAL=true"`

`kroma-validator  | t=2024-04-06T14:29:38+0000 lvl=info msg="initializing Validator"`

`kroma-validator  | t=2024-04-06T14:29:38+0000 lvl=eror msg="Unable to create validator config" err="could not dial eth client: tls: first record does not look like a TLS handshake"`

.env config
`KROMA_NODE__L1_RPC_ENDPOINT=http://10.0.0.91:8545`
`KROMA_VALIDATOR__L1_RPC_ENDPOINT=wss://10.0.0.91:8545`

### Expected Behavior?

There should be a way to ignore encryption -- and avoid these TLS Errors

### Standalone code or description to reproduce the issue

Configure RPC Endpoint to a local network node and run without encryption / proxy being enabled

**Comment by 0xHansLee** [comment]
Sorry for late response. Could you try with `ws` instead of `wss` for `KROMA_VALIDATOR__L1_RPC_ENDPOINT`?

**Comment by 0xHansLee** [comment]
I'll close this issue because I don't think it's a bug. If you have any issues related this issue, please re-open this issue with comments.
