### ISSUE TITLE
Missing 1.4.3 version on docker hub

### ISSUE THREAD

**Issue by SwatGuard** [kroma-network/kroma#331]
### Issue type

Build/Install

### Kroma version

1.4.3

### OS platform and distribution

any

### Node version

1.4.3

### Current behavior?

docker pull kromanetwork/node:v1.4.3
Error response from daemon: manifest for kromanetwork/node:v1.4.3 not found: manifest unknown: manifest unknown

### Expected Behavior?

Image should be pulled

### Standalone code or description to reproduce the issue

attempt to pull v 1.4.3 of kroma node from docker hub.

**Comment by 0xHansLee** [comment]
Thank you for letting us know. There was a temporary issue in building docker image of kroma-node. BTW, docker image for kroma-node v1.4.3 has been built. Could you try again?

**Comment by SwatGuard** [comment]
All good now. Thanks for fixing this.
