### ISSUE TITLE
err: ethClient.BlockByHash(txReceipt.BlockHash)

### ISSUE THREAD

**Issue by autoluckgmail** [kroma-network/kroma#341]
hashcode=0x7c6bbe3961a2f2fe72d56fc522a53f83402c248a8c388914335ecf76de0086bc
when using ethClient.BlockByHash(txReceipt.BlockHash) report err:transaction type not supported

**Comment by autoluckgmail** [comment]
go-eth package
I had try: 
github.com/ethereum/go-ethereum v1.14.6
github.com/ethereum/go-ethereum v1.13.14

**Comment by seolaoh** [comment]
`0x924709a4203de7797754ccaa07668262736bbedc7c3f34b1cdb01812ad719f81` is a transaction hash, right? You need to provide a block hash to that function. Additionally you need to use [kroma-geth](https://github.com/kroma-network/go-ethereum) to operate a Kroma node, and we recommend to use [kroma-up](https://github.com/kroma-network/kroma-up) to operate Kroma node.

**Comment by autoluckgmail** [comment]
could you support go-eth?

**Comment by 0xHansLee** [comment]
@autoluckgmail 
go-eth is for L1, but for L2 (Kroma), you need to use kroma-geth. It is quite different client. The right execution engine should be used for interaction with L2 consensus layer (kroma).

**Comment by seolaoh** [comment]
Since there are no more comments, we're closing it.
