### ISSUE TITLE
Prevent delay attacks

### ISSUE THREAD

**Issue by chokobole** [kroma-network/kroma#54]
### Issue Type

Feature Request

### Kroma Version

0.1.1

### Open Question

Let's say we have $1B worth of TVL in our L2 chain. An attacker could run the following scenario to consume this TVL.

Parameter
- interaction timeout: 1 hour
- proving timeout: 4 hour
- initial bonding amount: 1 ETH
- finalization period: 7 days
- 1 ETH: $2,000

1. posts an incorrect OutputRoot. This OutputRoot states that the attacker's address has all the TVLs in L2.
2. colludes with L1 validators to choose which challenges can be selected.
3. The attacker challenges against the wrong OutputRoot, completes 4 interactions, and waits for 1 proving timeout.
4. the challenge is resolved after 8 hours.
5. the challengers repeat this during the finalization period to ensure that the wrong OutputRoot is finalized.

Analyzing this scenario, we can see that

1) The finalization period is 24 * 7 hours, so the attacker needs to challenge 24 * 7 / 8 = 21 times to execute this attack.
2) After the challenge is over, the bonding amount required to challenge again is doubled, so the total required bonding amount is (2^21 -1 = 1 + 2 + ... + 2^20) * ETH.
3) Therefore, the attacker has about $4.2 B.

Is this attack viable, and if so, how to stop it?

Here are some simple ideas to prevent it

1. a Security Council intervention after a few timeouts.
2. use `collaborative interaction` like the [Goshen Network](https://goshen.network/) to allow other challengers to take over the challenge when it times out.

**Comment by 0xHansLee** [comment]
Another way to prevent it is to allow multiple challenges as done in Optimism.
